### ISSUE TITLE
How do you trigger the popup with a scope variable/data?

### ISSUE THREAD

**Issue by rutwick** [MarkoCen/angular-popup#1]
The documentation is incomplete. I had a hard time just to trigger the popup on clicking a link. I still can't figure out how to trigger it. Your example doesn't state that. Please can you guide?

**Comment by MarkoCen** [comment]
@rutwick 

It is really long time since last commit on this repo, I don't know if you still use ngPopup in your code:)
Anyway I modified the code recently, and now you can simply show/hide a dialog by toggling its `isShow` property. In your case:

``` html
<a ng-click="toggleDialog()">Toggle Dialog</a>
<ng-pop-up option="dialogOption"></ng-pop-up>
```

``` javascript
//In your controller

scope.dialogOption = {
    isShow: false //set dialog hided initially
};

scope.toggleDialog = function(){
   scope.dialogOption.isShow = !scope.dialogOption.isShow;
}
```
