### ISSUE TITLE
Package.json and bower.json version tags do not match release tag

### ISSUE THREAD

**Issue by kburson** [MarkoCen/angular-popup#4]
For release tag **0.4.0** 

the **package.json** file shows:
  `"version": "0.1.2",`

the **bower.json** shows:
`"version": "0.3.0",`

Please update these accordingly,

Thank you

**Comment by MarkoCen** [comment]
Hi,
I just update ngPopup on Bower and NPM with [v0.4.1](https://github.com/MarkoCen/ngPopup/releases/tag/v0.4.1)
