### ISSUE TITLE
Can we use this directive ngPopup to open multiple dialog with one directive only

### ISSUE THREAD

**Issue by hjindal1978** [MarkoCen/angular-popup#7]
Hi

i have been trying to use this directive to build a chat functionality and wanted to open multiple dialogs for different chat session for different users.

i added directive one time in to the HTML and also tried to add directive at run time 

Please suggest how can we achieve this functionality using this directive.

Regards,
Hemant Jindal

**Comment by MarkoCen** [comment]
Hi,

I am little bit confused what you trying to build, can you provide a plunker or jsFiddle?

if you trying to add multiple dialogs in one page, just simply add multiple `ngPopup` directives in page, and define different options for them,

if you trying to dynamic insert dialog into a page, you can use angular `$compile` service to link html template with a scope, then append the compiled template into DOM

**Comment by MarkoCen** [comment]
Close this issue due to no further response..
